id: P009630
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17122
  title: སྐུ་གསུམ་གྱི་རྣམ་གཞག་རབ་གསལ་སྒྲོན་མེ་དང་སྔགས་བཀླག་ཐབས་བསྡུས་པ།
  author: ''
  volumes:
    e9972546058c4cd6af1fbacede6bd29a:
      image_group_id: I8LS17132
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
