id: IA4ACC8AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:22:52+00:00'
last_modified: '2022-06-08T12:23:31.679803+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17122
  title: སྐུ་གསུམ་གྱི་རྣམ་གཞག་རབ་གསལ་སྒྲོན་མེ་དང་སྔགས་བཀླག་ཐབས་བསྡུས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C59A:
      image_group_id: I8LS17132
      title: ''
      total_pages: 174
      order: 1
      base_file: C59A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
